### ISSUE TITLE
Zeitverzögertes schreiben der accounts

### ISSUE THREAD

**Issue by pdaus1405** [Tracer1337/auto-upload#2]
Da gerne alle Prozesse gleichzeitig in die accounts.json ihre daten schreiben wollen, kommt es gerne mal zu crashes 

daher sollte das starten evtl etwas verzögert werden der einzelnen nodes? 
oder eine andere möglichkeit

**Comment by Tracer1337** [comment]
Das Problem trat bei mir nicht auf. Ich schlage dennoch vor, die Daten in eine SQLite3 Datenbank zu speichern. Geht easy mit https://www.npmjs.com/package/sqlite3. Dann sollten parallele Schreibvorgänge kein Problem mehr sein.

**Comment by pdaus1405** [comment]
und dann die sqlite datenbank datei mit speichern?

**Comment by Tracer1337** [comment]
Die Datei im Versioncontrol zu speichern finde ich nicht sinnvoll, aber ich könnte eine Remote Datenbank bereitstellen, wenn der Gerät-Unabhängige Zugriff gewünscht ist.

**Comment by Tracer1337** [comment]
Damit verbunden kann auch die Verwendung bestehender Account Implementiert werden, anstatt für jede Ausführung einen neuen Account zu erstellen.

**Comment by pdaus1405** [comment]
wäre eine idee, wenn es so viele nutzen
auch damit evtl nicht doppelte mail registriert wird oder so

und man so einen überblick bekommt wie viel speicher schon vebraucht wird

und das weiter benutzen des accounts
nur wenn noch speicher frei ist
da müsste man regelmäßig dann page reloads machen und das abfragen
und dann für die einfachhalber auch den stand in die db :D 


aber lohnt sich das ganze noch? 
die seite nicht wieder kommt

**Comment by Tracer1337** [comment]
Wenn die Seite nicht wiederkommt haben wir gewonnen 😄 . Das Feature wird eingebaut, wenn die Seite wieder verfügbar ist. Will nicht Zeit investieren und es nie ausprobieren können 🙃

**Comment by Tracer1337** [comment]
Ich denke nicht, dass ich / wir daran weiterarbeiten werden. Wenn wieder Interesse besteht, öffne ich das Issue wieder.
