### ISSUE TITLE
Mehrmals gleichen account?

### ISSUE THREAD

**Issue by pdaus1405** [Tracer1337/auto-upload#3]
Bei zb 4 Workern nehmen alle 4 den gleichen nutzer/mail zum registrieren

ich denke dies ist nicht so sinnvoll
denn dadurch wird 4 mal der gleiche eintrag in der accounts.json angelegt

![image](https://user-images.githubusercontent.com/16647268/113252162-c406f380-92c3-11eb-922e-c3b6db7b6b24.png)

**Comment by Tracer1337** [comment]
Gefixed in https://github.com/Tracer1337/auto-upload/commit/6bc8e10faa581abec266aeb3c54c595e4882da83
